In [10]:
import pandas as pd
df=pd.read_csv("data.csv")
print(df.head())

                  date      price  bedrooms  bathrooms  sqft_living  sqft_lot  \
0  2014-05-02 00:00:00   313000.0       3.0       1.50         1340      7912
1  2014-05-02 00:00:00  2384000.0       5.0       2.50         3650      9050
2  2014-05-02 00:00:00   342000.0       3.0       2.00         1930     11947
3  2014-05-02 00:00:00   420000.0       3.0       2.25         2000      8030
4  2014-05-02 00:00:00   550000.0       4.0       2.50         1940     10500

   floors  waterfront  view  condition  sqft_above  sqft_basement  yr_built  \
0     1.5           0     0          3        1340              0      1955
1     2.0           0     4          5        3370            280      1921
2     1.0           0     0          4        1930              0      1966
3     1.0           0     0          4        1000           1000      1963
4     1.0           0     0          4        1140            800      1976

   yr_renovated                    street       city  statezip country
0          2005      18810 Densmore Ave N  Shoreline  WA 98133     USA
1             0           709 W Blaine St    Seattle  WA 98119     USA
2             0  26206-26214 143rd Ave SE       Kent  WA 98042     USA
3             0           857 170th Pl NE   Bellevue  WA 98008     USA
4          1992         9105 170th Ave NE    Redmond  WA 98052     USA

In [11]:
df.columns

Index(['date', 'price', 'bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot',
       'floors', 'waterfront', 'view', 'condition', 'sqft_above',
       'sqft_basement', 'yr_built', 'yr_renovated', 'street', 'city',
       'statezip', 'country'],
      dtype='object')

In [26]:
X = df[['bedrooms',
       'bathrooms',
       'sqft_living',
       'sqft_lot',
       'floors',
       'waterfront',
       'view',
       'condition',
       'sqft_above',
       'sqft_basement',
       'yr_built',
       'yr_renovated']]
y = df[['price']]

In [27]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10)
X_train

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,sqft_above,sqft_basement,yr_built,yr_renovated
1893,3.0,2.50,1690,1553,2.5,0,0,3,1690,0,2007,0
1364,4.0,2.25,1940,9144,1.0,0,0,4,1430,510,1956,0
1951,6.0,4.50,3902,3880,3.0,0,4,4,2782,1120,1977,0
2766,4.0,2.50,2410,4780,2.0,0,0,3,2410,0,2000,0
2929,3.0,2.00,1430,3480,1.0,0,0,3,980,450,1947,2012
...,...,...,...,...,...,...,...,...,...,...,...,...
2009,3.0,2.25,1530,1245,2.0,0,0,3,1050,480,2014,0
1180,4.0,2.00,980,10640,1.0,0,0,5,980,0,1978,0
3441,2.0,1.50,1370,1221,2.0,0,0,3,1080,290,2008,0
1344,3.0,2.00,1840,4750,1.0,0,0,5,1010,830,1951,0
1289,3.0,2.00,1490,8371,1.5,0,0,3,1490,0,1984,0

In [28]:
y_train

          price
1893   640000.0
1364   495000.0
1951  1300000.0
2766   440000.0
2929   450000.0
...         ...
2009   465000.0
1180   295000.0
3441   446000.0
1344   730001.0
1289   255000.0

[3680 rows x 1 columns]

In [29]:
from sklearn.linear_model import LinearRegression
clf=LinearRegression()

In [30]:
clf.fit(X_train,y_train)

LinearRegression()

In [31]:
clf.predict(X_train)

array([[ 415676.29272689],
       [ 480839.92756496],
       [1175745.73643501],
       ...,
       [ 304322.27113802],
       [ 533237.59602608],
       [ 347693.56862653]], shape=(3680, 1))

In [32]:
clf.score(X_test,y_test)

0.44630339322958534