In [4]:
import pandas as pd
df=pd.read_csv("Advertising.csv")

In [5]:
df.columns

Index(['Unnamed: 0', 'TV Ad Budget ($)', 'Radio Ad Budget ($)',
       'Newspaper Ad Budget ($)', 'Sales ($)'],
      dtype='object')

In [6]:
df.head(10)

,Unnamed: 0,TV Ad Budget ($),Radio Ad Budget ($),Newspaper Ad Budget ($),Sales ($)
0,1,230.1,37.8,69.2,22.1
1,2,44.5,39.3,45.1,10.4
2,3,17.2,45.9,69.3,9.3
3,4,151.5,41.3,58.5,18.5
4,5,180.8,10.8,58.4,12.9
5,6,8.7,48.9,75.0,7.2
6,7,57.5,32.8,23.5,11.8
7,8,120.2,19.6,11.6,13.2
8,9,8.6,2.1,1.0,4.8
9,10,199.8,2.6,21.2,10.6

In [27]:
X = df[['Newspaper Ad Budget ($)',
     'TV Ad Budget ($)',
     'Radio Ad Budget ($)']]
y = df[['Sales ($)']]

In [28]:
print(type(X))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.frame.DataFrame'>

In [29]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=10)
X_train

     Newspaper Ad Budget ($)  TV Ad Budget ($)  Radio Ad Budget ($)
190                      5.8              39.5                 41.1
7                       11.6             120.2                 19.6
26                      12.6             142.9                 29.3
138                     20.5              43.0                 25.9
58                      37.7             210.8                 49.6
..                       ...               ...                  ...
113                     10.7             209.6                 20.6
64                      28.9             131.1                 42.8
15                      52.9             195.4                 47.7
125                     25.9              87.2                 11.8
9                       21.2             199.8                  2.6

[160 rows x 3 columns]

In [30]:
y_train

     Sales ($)
190       10.8
7         13.2
26        15.0
138        9.6
58        23.8
..         ...
113       15.9
64        18.0
15        22.4
125       10.6
9         10.6

[160 rows x 1 columns]

In [31]:
from sklearn.linear_model import LinearRegression
clf=LinearRegression()

In [33]:
clf.fit(X_train,y_train)

LinearRegression()

In [35]:
clf.predict(X_train)

array([[12.92028367],
       [12.28099653],
       [15.1487058 ],
       [10.10054313],
       [21.99161246],
       [10.76747572],
       [14.7661212 ],
       [15.05785147],
       [ 8.916832  ],
       [12.05627807],
       [ 8.377599  ],
       [13.87664564],
       [23.02502886],
       [17.51275854],
       [14.57984468],
       [ 5.93510118],
       [24.74044038],
       [17.80201748],
       [10.05985156],
       [ 8.36363062],
       [ 7.14851131],
       [14.59817458],
       [16.39674242],
       [13.26888438],
       [18.67152907],
       [18.94060348],
       [13.98744306],
       [15.65288507],
       [12.13366533],
       [ 9.38648223],
       [14.52019973],
       [10.22712641],
       [ 8.30724473],
       [13.82043061],
       [17.13600698],
       [16.3789032 ],
       [14.77656602],
       [11.26256506],
       [ 6.72008424],
       [17.37625531],
       [11.71328264],
       [14.46160012],
       [ 7.73207983],
       [ 7.64554012],
       [16.14425695],
       [15.39546845],
       [20.05274825],
       [18.13413086],
       [23.10728723],
       [16.67969734],
       [ 9.49779947],
       [18.44950617],
       [10.40442798],
       [20.84183307],
       [18.41684259],
       [ 9.34843592],
       [17.74404443],
       [16.45800549],
       [23.27907498],
       [18.45353356],
       [15.97764425],
       [ 6.36103017],
       [ 9.70729862],
       [17.13000423],
       [15.20071512],
       [ 8.87848374],
       [15.36071069],
       [12.39794329],
       [ 8.63463214],
       [21.45981526],
       [ 8.08807912],
       [15.32770902],
       [ 9.76966795],
       [14.23758425],
       [12.13451794],
       [ 8.85860894],
       [17.11935582],
       [10.93850543],
       [13.91846236],
       [17.28555149],
       [ 6.79693183],
       [ 6.40997989],
       [15.12369928],
       [15.15656941],
       [12.0632471 ],
       [22.36828575],
       [10.15539038],
       [ 5.66468331],
       [12.68628274],
       [20.30366999],
       [ 7.69744834],
       [ 3.84783431],
       [12.52238923],
       [12.18961062],
       [10.24112968],
       [ 9.74285686],
       [13.1270985 ],
       [19.25480175],
       [ 9.22751047],
       [12.56742905],
       [19.9236434 ],
       [19.33571533],
       [14.44071945],
       [14.39179495],
       [10.59331354],
       [10.7557679 ],
       [15.71747012],
       [ 4.72963128],
       [12.78651035],
       [20.69181294],
       [17.32442488],
       [ 6.75049028],
       [10.63904265],
       [10.06687696],
       [18.14731997],
       [11.97024912],
       [21.1358055 ],
       [10.20775055],
       [16.94319062],
       [23.3982257 ],
       [12.89284102],
       [11.47572656],
       [ 8.07132758],
       [ 9.72661552],
       [17.19186572],
       [10.80317232],
       [21.45296221],
       [11.87769316],
       [19.13189906],
       [18.4118813 ],
       [11.00728966],
       [18.34760808],
       [ 8.9759693 ],
       [14.00988703],
       [13.80188009],
       [24.00068883],
       [18.74809157],
       [16.66624627],
       [13.4886302 ],
       [ 7.21746233],
       [11.88816572],
       [20.28859213],
       [19.83557056],
       [13.70989199],
       [13.04744451],
       [13.19411674],
       [11.21567561],
       [16.36117497],
       [20.48370749],
       [ 9.95107876],
       [ 4.03452198],
       [ 5.61115526],
       [10.00853627],
       [15.6661254 ],
       [15.30764884],
       [16.38970615],
       [17.20720507],
       [20.91611405],
       [ 9.2958516 ],
       [12.45553856]])

In [37]:
clf.score(X_test,y_test)

0.8353672324670596

In [39]:
print(clf.coef_)
print(clf.intercept_)

[[-0.00222879  0.0437726   0.19343299]]
[3.25409711]