In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("tested.csv")

In [3]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age             86
SibSp            0
Parch            0
Ticket           0
Fare             1
Cabin          327
Embarked         0
dtype: int64

In [5]:
df['Sex'] = df['Sex'].map({
    'male':0,
    'female':1
})

In [6]:
x=df[['PassengerId',
      'Pclass',
      'Sex', 
      'SibSp',
      'Parch',]]
y=df[['Survived']]

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)
x_train

     PassengerId  Pclass  Sex  SibSp  Parch
281         1173       3    0      1      1
52           944       2    1      2      1
303         1195       3    0      0      0
202         1094       1    0      1      0
181         1073       1    0      1      1
..           ...     ...  ...    ...    ...
369         1261       2    0      0      0
320         1212       3    0      0      0
15           907       2    1      1      0
125         1017       3    1      0      1
265         1157       3    0      0      0

[334 rows x 5 columns]

In [8]:
y_train

     Survived
281         0
52          1
303         0
202         0
181         0
..        ...
369         0
320         0
15          1
125         1
265         0

[334 rows x 1 columns]

In [9]:
from sklearn.linear_model import LogisticRegression
clf=LogisticRegression()

In [10]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",0,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",1,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",0,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",0,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",1,22.0,1,1,3101298,12.2875,NaN,S
5,897,0,3,"Svensson, Mr. Johan Cervin",0,14.0,0,0,7538,9.2250,NaN,S
6,898,1,3,"Connolly, Miss. Kate",1,30.0,0,0,330972,7.6292,NaN,Q
7,899,0,2,"Caldwell, Mr. Albert Francis",0,26.0,1,1,248738,29.0000,NaN,S
8,900,1,3,"Abrahim, Mrs. Joseph (Sophie Halaut Easu)",1,18.0,0,0,2657,7.2292,NaN,C
9,901,0,3,"Davies, Mr. John Samuel",0,21.0,2,0,A/4 48871,24.1500,NaN,S

In [11]:
clf.fit(x_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: divide by zero encountered in matmul
  raw_prediction = X @ weights + intercept
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: overflow encountered in matmul
  raw_prediction = X @ weights + intercept
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_linear_loss.py:200: RuntimeWarning: invalid value encountered in matmul
  raw_prediction = X @ weights + intercept
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [12]:
clf.predict(x_train)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0,
       0, 1, 1, 0])

In [13]:
clf.predict_proba(x_train)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

array([[0.97805664, 0.02194336],
       [0.02836746, 0.97163254],
       [0.98286855, 0.01713145],
       [0.95823402, 0.04176598],
       [0.95204756, 0.04795244],
       [0.92429348, 0.07570652],
       [0.96676514, 0.03323486],
       [0.97817659, 0.02182341],
       [0.96491162, 0.03508838],
       [0.05416002, 0.94583998],
       [0.98066881, 0.01933119],
       [0.05739942, 0.94260058],
       [0.04432648, 0.95567352],
       [0.04527423, 0.95472577],
       [0.97223589, 0.02776411],
       [0.97855735, 0.02144265],
       [0.98697326, 0.01302674],
       [0.98274379, 0.01725621],
       [0.97663874, 0.02336126],
       [0.97146995, 0.02853005],
       [0.01895424, 0.98104576],
       [0.97519315, 0.02480685],
       [0.05896595, 0.94103405],
       [0.9653944 , 0.0346056 ],
       [0.97042886, 0.02957114],
       [0.95938226, 0.04061774],
       [0.93817228, 0.06182772],
       [0.97401296, 0.02598704],
       [0.96451331, 0.03548669],
       [0.96905718, 0.03094282],
       [0.05403409, 0.94596591],
       [0.9831969 , 0.0168031 ],
       [0.97417147, 0.02582853],
       [0.94487852, 0.05512148],
       [0.98500467, 0.01499533],
       [0.97528948, 0.02471052],
       [0.02402975, 0.97597025],
       [0.98162455, 0.01837545],
       [0.03553202, 0.96446798],
       [0.95947612, 0.04052388],
       [0.97608849, 0.02391151],
       [0.97343771, 0.02656229],
       [0.05193519, 0.94806481],
       [0.95536939, 0.04463061],
       [0.9659653 , 0.0340347 ],
       [0.96584798, 0.03415202],
       [0.98253389, 0.01746611],
       [0.02948041, 0.97051959],
       [0.05219837, 0.94780163],
       [0.96303234, 0.03696766],
       [0.05130763, 0.94869237],
       [0.97505114, 0.02494886],
       [0.9765612 , 0.0234388 ],
       [0.97414788, 0.02585212],
       [0.93614345, 0.06385655],
       [0.97158495, 0.02841505],
       [0.97599126, 0.02400874],
       [0.9736366 , 0.0263634 ],
       [0.98419943, 0.01580057],
       [0.97396143, 0.02603857],
       [0.98085454, 0.01914546],
       [0.97639162, 0.02360838],
       [0.9822358 , 0.0177642 ],
       [0.98183156, 0.01816844],
       [0.04796655, 0.95203345],
       [0.06082011, 0.93917989],
       [0.97522583, 0.02477417],
       [0.97936815, 0.02063185],
       [0.97920638, 0.02079362],
       [0.08878345, 0.91121655],
       [0.97915271, 0.02084729],
       [0.96125847, 0.03874153],
       [0.96289004, 0.03710996],
       [0.98023791, 0.01976209],
       [0.96739191, 0.03260809],
       [0.98429816, 0.01570184],
       [0.04609185, 0.95390815],
       [0.0616248 , 0.9383752 ],
       [0.97776896, 0.02223104],
       [0.97921844, 0.02078156],
       [0.97260686, 0.02739314],
       [0.96498097, 0.03501903],
       [0.97033617, 0.02966383],
       [0.0541947 , 0.9458053 ],
       [0.06354639, 0.93645361],
       [0.09123709, 0.90876291],
       [0.97862679, 0.02137321],
       [0.98347914, 0.01652086],
       [0.0465716 , 0.9534284 ],
       [0.07608428, 0.92391572],
       [0.97711793, 0.02288207],
       [0.96927778, 0.03072222],
       [0.96312555, 0.03687445],
       [0.98323751, 0.01676249],
       [0.97247543, 0.02752457],
       [0.95180147, 0.04819853],
       [0.04857102, 0.95142898],
       [0.04140937, 0.95859063],
       [0.97892465, 0.02107535],
       [0.96581722, 0.03418278],
       [0.96504946, 0.03495054],
       [0.94911051, 0.05088949],
       [0.98270201, 0.01729799],
       [0.98235091, 0.01764909],
       [0.96226957, 0.03773043],
       [0.95711959, 0.04288041],
       [0.96762399, 0.03237601],
       [0.09099793, 0.90900207],
       [0.04198969, 0.95801031],
       [0.95845395, 0.04154605],
       [0.9824916 , 0.0175084 ],
       [0.04214599, 0.95785401],
       [0.04801289, 0.95198711],
       [0.05383053, 0.94616947],
       [0.94827203, 0.05172797],
       [0.98341815, 0.01658185],
       [0.96456278, 0.03543722],
       [0.94041716, 0.05958284],
       [0.98047486, 0.01952514],
       [0.95593386, 0.04406614],
       [0.98437405, 0.01562595],
       [0.94905746, 0.05094254],
       [0.06286742, 0.93713258],
       [0.98094675, 0.01905325],
       [0.06998155, 0.93001845],
       [0.9811157 , 0.0188843 ],
       [0.97091921, 0.02908079],
       [0.9755256 , 0.0244744 ],
       [0.97901718, 0.02098282],
       [0.9625213 , 0.0374787 ],
       [0.97254122, 0.02745878],
       [0.05109352, 0.94890648],
       [0.9739506 , 0.0260494 ],
       [0.97340444, 0.02659556],
       [0.08153534, 0.91846466],
       [0.05413367, 0.94586633],
       [0.9716995 , 0.0283005 ],
       [0.07113925, 0.92886075],
       [0.0696619 , 0.9303381 ],
       [0.04773425, 0.95226575],
       [0.05390844, 0.94609156],
       [0.09376519, 0.90623481],
       [0.06398714, 0.93601286],
       [0.945551  , 0.054449  ],
       [0.97591557, 0.02408443],
       [0.04929739, 0.95070261],
       [0.97644052, 0.02355948],
       [0.9672256 , 0.0327744 ],
       [0.05093738, 0.94906262],
       [0.96192291, 0.03807709],
       [0.11227339, 0.88772661],
       [0.97989303, 0.02010697],
       [0.0527429 , 0.9472571 ],
       [0.98496828, 0.01503172],
       [0.98143223, 0.01856777],
       [0.98141201, 0.01858799],
       [0.98093246, 0.01906754],
       [0.97310653, 0.02689347],
       [0.04970001, 0.95029999],
       [0.97061819, 0.02938181],
       [0.95380243, 0.04619757],
       [0.96642261, 0.03357739],
       [0.96788346, 0.03211654],
       [0.98368473, 0.01631527],
       [0.97312653, 0.02687347],
       [0.04467289, 0.95532711],
       [0.04877095, 0.95122905],
       [0.97096707, 0.02903293],
       [0.98578369, 0.01421631],
       [0.95425216, 0.04574784],
       [0.97138042, 0.02861958],
       [0.96969198, 0.03030802],
       [0.95751858, 0.04248142],
       [0.03594416, 0.96405584],
       [0.98106036, 0.01893964],
       [0.97227713, 0.02772287],
       [0.96770099, 0.03229901],
       [0.94322493, 0.05677507],
       [0.963399  , 0.036601  ],
       [0.05361019, 0.94638981],
       [0.06532652, 0.93467348],
       [0.98156629, 0.01843371],
       [0.96812534, 0.03187466],
       [0.07111104, 0.92888896],
       [0.05284872, 0.94715128],
       [0.11276487, 0.88723513],
       [0.95216784, 0.04783216],
       [0.9807619 , 0.0192381 ],
       [0.05024867, 0.94975133],
       [0.9743841 , 0.0256159 ],
       [0.07591811, 0.92408189],
       [0.98375671, 0.01624329],
       [0.03820373, 0.96179627],
       [0.97192951, 0.02807049],
       [0.97304206, 0.02695794],
       [0.04360245, 0.95639755],
       [0.97644828, 0.02355172],
       [0.09772496, 0.90227504],
       [0.98131124, 0.01868876],
       [0.97015744, 0.02984256],
       [0.97196894, 0.02803106],
       [0.0287157 , 0.9712843 ],
       [0.97870468, 0.02129532],
       [0.97935269, 0.02064731],
       [0.98402969, 0.01597031],
       [0.94993613, 0.05006387],
       [0.97174151, 0.02825849],
       [0.94815118, 0.05184882],
       [0.02907293, 0.97092707],
       [0.02698396, 0.97301604],
       [0.98071541, 0.01928459],
       [0.97374069, 0.02625931],
       [0.97843771, 0.02156229],
       [0.05359271, 0.94640729],
       [0.06783112, 0.93216888],
       [0.95671377, 0.04328623],
       [0.97850565, 0.02149435],
       [0.98581814, 0.01418186],
       [0.98410685, 0.01589315],
       [0.04923793, 0.95076207],
       [0.94491403, 0.05508597],
       [0.97971336, 0.02028664],
       [0.9831562 , 0.0168438 ],
       [0.97925294, 0.02074706],
       [0.01779477, 0.98220523],
       [0.03921339, 0.96078661],
       [0.07514214, 0.92485786],
       [0.98598914, 0.01401086],
       [0.06112542, 0.93887458],
       [0.95883429, 0.04116571],
       [0.02388718, 0.97611282],
       [0.97250037, 0.02749963],
       [0.04413646, 0.95586354],
       [0.98210652, 0.01789348],
       [0.96481427, 0.03518573],
       [0.93731969, 0.06268031],
       [0.96569644, 0.03430356],
       [0.0537095 , 0.9462905 ],
       [0.97372977, 0.02627023],
       [0.96815932, 0.03184068],
       [0.97964916, 0.02035084],
       [0.97981095, 0.02018905],
       [0.06200862, 0.93799138],
       [0.97990808, 0.02009192],
       [0.96793095, 0.03206905],
       [0.97745515, 0.02254485],
       [0.05303659, 0.94696341],
       [0.97005152, 0.02994848],
       [0.06568486, 0.93431514],
       [0.05107717, 0.94892283],
       [0.08187258, 0.91812742],
       [0.03345008, 0.96654992],
       [0.94094261, 0.05905739],
       [0.03346908, 0.96653092],
       [0.96127436, 0.03872564],
       [0.9679442 , 0.0320558 ],
       [0.05993907, 0.94006093],
       [0.97426096, 0.02573904],
       [0.96689846, 0.03310154],
       [0.98149091, 0.01850909],
       [0.96937866, 0.03062134],
       [0.03568085, 0.96431915],
       [0.96095037, 0.03904963],
       [0.09625367, 0.90374633],
       [0.95933412, 0.04066588],
       [0.06489236, 0.93510764],
       [0.03678589, 0.96321411],
       [0.97141353, 0.02858647],
       [0.02567043, 0.97432957],
       [0.97994145, 0.02005855],
       [0.04591261, 0.95408739],
       [0.98227868, 0.01772132],
       [0.07069154, 0.92930846],
       [0.04492691, 0.95507309],
       [0.9743226 , 0.0256774 ],
       [0.96592648, 0.03407352],
       [0.98639129, 0.01360871],
       [0.97007372, 0.02992628],
       [0.95398527, 0.04601473],
       [0.97483344, 0.02516656],
       [0.98694158, 0.01305842],
       [0.07275381, 0.92724619],
       [0.03055509, 0.96944491],
       [0.06103868, 0.93896132],
       [0.05452205, 0.94547795],
       [0.95132201, 0.04867799],
       [0.98605697, 0.01394303],
       [0.97160605, 0.02839395],
       [0.04157537, 0.95842463],
       [0.07053004, 0.92946996],
       [0.98240674, 0.01759326],
       [0.09059163, 0.90940837],
       [0.94725569, 0.05274431],
       [0.98359866, 0.01640134],
       [0.03091918, 0.96908082],
       [0.95449278, 0.04550722],
       [0.95811829, 0.04188171],
       [0.98214971, 0.01785029],
       [0.96097735, 0.03902265],
       [0.97974705, 0.02025295],
       [0.03583583, 0.96416417],
       [0.10558707, 0.89441293],
       [0.98019673, 0.01980327],
       [0.95022605, 0.04977395],
       [0.0250725 , 0.9749275 ],
       [0.98642428, 0.01357572],
       [0.03277859, 0.96722141],
       [0.9557012 , 0.0442988 ],
       [0.06048607, 0.93951393],
       [0.07014189, 0.92985811],
       [0.03602953, 0.96397047],
       [0.96942401, 0.03057599],
       [0.03093447, 0.96906553],
       [0.98518533, 0.01481467],
       [0.98114863, 0.01885137],
       [0.9591247 , 0.0408753 ],
       [0.05882066, 0.94117934],
       [0.04083444, 0.95916556],
       [0.04861411, 0.95138589],
       [0.955297  , 0.044703  ],
       [0.06143855, 0.93856145],
       [0.96475062, 0.03524938],
       [0.98080827, 0.01919173],
       [0.94887227, 0.05112773],
       [0.04491618, 0.95508382],
       [0.986878  , 0.013122  ],
       [0.97911805, 0.02088195],
       [0.03713333, 0.96286667],
       [0.97357336, 0.02642664],
       [0.98074747, 0.01925253],
       [0.98355891, 0.01644109],
       [0.03147836, 0.96852164],
       [0.05406413, 0.94593587],
       [0.98122076, 0.01877924]])

In [14]:
clf.score(x_test,y_test)

1.0

In [15]:
clf.score(x_train,y_train)

/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: divide by zero encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: overflow encountered in matmul
  ret = a @ b
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sklearn/utils/extmath.py:203: RuntimeWarning: invalid value encountered in matmul
  ret = a @ b

1.0